Data team
WomenPlusPlus/deploy-impact-23-kpi-1 pull request #17
Opened 2023-10-05 09:55 UTC by caracfinlay

Sql script for database schema, including view for current KPI values and trigger for handling dates.

2023-10-06 20:14 UTC, daczczcz1 requested changes
Added some comments, overall it looks good - I would also rebase the branch on top of master and squash the commits (if not into just one, then maybe two: one for the SQL scripts another for the data, though it can be just one commit IMHO).

2023-10-06 20:14 UTC, daczczcz1 commented on data-team/notebooks/schema.sql
> +    unit unit,
Perhaps it should be not null as well?

2023-10-06 20:14 UTC, daczczcz1 commented on data-team/notebooks/schema.sql
> +    created_at timestamp default current_timestamp,
Not null again?

2023-10-06 20:14 UTC, daczczcz1 commented on data-team/notebooks/schema.sql
> +    created_at timestamp default current_timestamp,
Not null again?

2023-10-06 20:14 UTC, daczczcz1 commented on data-team/notebooks/schema.sql
> +    created_at timestamp default current_timestamp,
Not null again?

2023-10-08 14:50 UTC, Aurelieph commented on data-team/notebooks/schema.sql
> +
new 2 views 
```suggestion
create view
  public.kpi_values_period_standardized as
select distinct
  on (
    kd.kpi_id,
    (
      case
        when kd.periodicity = 'yearly'::periodicity then date_trunc(
          'year'::text,
          t1.period_date::timestamp with time zone
        ) + '1 year'::interval - '1 day'::interval
        when kd.periodicity = 'monthly'::periodicity then date_trunc(
          'month'::text,
          t1.period_date::timestamp with time zone
        ) + '1 mon'::interval - '1 day'::interval
        when kd.periodicity = 'quarterly'::periodicity then date_trunc(
          'quarter'::text,
          t1.period_date::timestamp with time zone
        ) + '3 mons'::interval - '1 day'::interval
        when kd.periodicity = 'weekly'::periodicity then date_trunc(
          'week'::text,
          t1.period_date::timestamp with time zone
        ) + '7 days'::interval - '1 day'::interval
        else t1.period_date::timestamp with time zone
      end
    ),
    t1.circle_id
  ) t1.kpi_value_history_id,
  t1.kpi_id,
  t1.circle_id,
  t1.user_id,
  t1.value,
  t1.period_date,
  t1.action,
  t1.created_at,
  kd.periodicity as kpi_periodicity,
  case
    when kd.periodicity = 'yearly'::periodicity then date_trunc(
      'year'::text,
      t1.period_date::timestamp with time zone
    ) + '1 year'::interval - '1 day'::interval
    when kd.periodicity = 'monthly'::periodicity then date_trunc(
      'month'::text,
      t1.period_date::timestamp with time zone
    ) + '1 mon'::interval - '1 day'::interval
    when kd.periodicity = 'quarterly'::periodicity then date_trunc(
      'quarter'::text,
      t1.period_date::timestamp with time zone
    ) + '3 mons'::interval - '1 day'::interval
    when kd.periodicity = 'weekly'::periodicity then date_trunc(
      'week'::text,
      t1.period_date::timestamp with time zone
    ) + '7 days'::interval - '1 day'::interval
    else t1.period_date::timestamp with time zone
  end as standardized_date
from
  kpi_values_history t1
  join kpi_definition kd on t1.kpi_id = kd.kpi_id
order by
  kd.kpi_id,
  (
    case
      when kd.periodicity = 'yearly'::periodicity then date_trunc(
        'year'::text,
        t1.period_date::timestamp with time zone
      ) + '1 year'::interval - '1 day'::interval
      when kd.periodicity = 'monthly'::periodicity then date_trunc(
        'month'::text,
        t1.period_date::timestamp with time zone
      ) + '1 mon'::interval - '1 day'::interval
      when kd.periodicity = 'quarterly'::periodicity then date_trunc(
        'quarter'::text,
        t1.period_date::timestamp with time zone
      ) + '3 mons'::interval - '1 day'::interval
      when kd.periodicity = 'weekly'::periodicity then date_trunc(
        'week'::text,
        t1.period_date::timestamp with time zone
      ) + '7 days'::interval - '1 day'::interval
      else t1.period_date::timestamp with time zone
    end
  ) desc,
  t1.circle_id,
  t1.created_at desc;
  
  create view
  public.kpi_definition_with_latest_values as
select
  ckd.circle_kpidef_id,
  ckd.circle_id,
  kd.kpi_id,
  kd.kpi_name,
  kd.description,
  kd.periodicity,
  kd.value_min,
  kd.value_max,
  kd.unit,
  kd.created_at as kpi_created_at,
  kd.updated_at as kpi_updated_at,
  t1.latest_value,
  t1.latest_user_id,
  t1.latest_standardized_date
from
  circle_kpi_definition ckd
  join kpi_definition kd on ckd.kpi_id = kd.kpi_id
  left join (
    select
      kv.kpi_id,
      kv.circle_id,
      kv.standardized_date as latest_standardized_date,
      kv.value as latest_value,
      kv.user_id as latest_user_id
    from
      kpi_values_period_standardized kv
      join (
        select
          kpi_values_period_standardized.kpi_id,
          kpi_values_period_standardized.circle_id,
          max(kpi_values_period_standardized.standardized_date) as max_standardized_date
        from
          kpi_values_period_standardized
        group by
          kpi_values_period_standardized.kpi_id,
          kpi_values_period_standardized.circle_id
      ) max_dates on kv.kpi_id = max_dates.kpi_id
      and kv.circle_id = max_dates.circle_id
      and kv.standardized_date = max_dates.max_standardized_date
  ) t1 on ckd.kpi_id = t1.kpi_id
  and ckd.circle_id = t1.circle_id;
```

2023-10-17 14:32 UTC, closed without merging